/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Qube.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Qube.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.065, 0.391, 0.044]}>
        <mesh geometry={nodes.Cube015.geometry} material={materials.base} />
        <mesh geometry={nodes.Cube015_1.geometry} material={materials.whitelight} />
        <mesh geometry={nodes.Cube015_2.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube015_3.geometry} material={materials.blackmetal} />
        <mesh geometry={nodes.Cube015_4.geometry} material={materials.orange} />
        <mesh geometry={nodes.Cube015_5.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.Cube003.geometry} material={materials.blackmetal} position={[-0.94, 0.45, -0.014]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[-0.237, -0.493, 0.246]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} position={[-0.329, -0.409, 0.214]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} position={[-0.547, -0.447, 0.172]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={nodes.Cylinder003.material} position={[-0.399, -0.442, 0.411]} />
      <mesh geometry={nodes.Cylinder005.geometry} material={nodes.Cylinder005.material} position={[-0.299, -0.336, 0.534]} />
      <mesh geometry={nodes.Cylinder006.geometry} material={nodes.Cylinder006.material} position={[-0.399, -0.442, 0.527]} />
      <mesh geometry={nodes.Cylinder007.geometry} material={nodes.Cylinder007.material} position={[-0.299, -0.288, 0.644]} />
      <mesh geometry={nodes.Cylinder008.geometry} material={nodes.Cylinder008.material} position={[-0.399, -0.353, 0.589]} />
      <mesh geometry={nodes.Cylinder009.geometry} material={nodes.Cylinder009.material} position={[-0.363, -0.393, 0.246]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['glass.001']} position={[-0.562, -0.507, 0.585]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.003']} position={[-0.681, -0.395, 0.702]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['glass.001']} position={[-0.415, 0.925, -0.021]} />
      <group position={[0.026, 0.994, -0.039]}>
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.blackmetal} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cube002_3.geometry} material={materials['Material.009']} />
      </group>
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.012']} position={[0.182, 0.094, -0.995]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['glass.001']} position={[0.82, 0.091, -0.788]} />
    </group>
  )
}

useGLTF.preload('/Qube.gltf')
