/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 blazer.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/blazer.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.long_sleeve_blazer.geometry} material={materials.fabric_texture} position={[-0.008, 0.035, 0.052]} />
      <mesh geometry={nodes.long_sleeve_blazer002.geometry} material={materials.fabric_texture} position={[-0.009, 0.3, 0.103]} />
      <mesh geometry={nodes.long_sleeve_blazer003.geometry} material={materials.fabric_texture} position={[-0.007, 0.147, -0.065]} />
      <mesh geometry={nodes.long_sleeve_blazer004.geometry} material={materials.fabric_texture} position={[-0.009, -0.077, 0.083]} />
      <mesh geometry={nodes.Circle004.geometry} material={materials['Material.002']} position={[0.002, -0.15, -0.113]}>
        <mesh geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} />
      </mesh>
      <mesh geometry={nodes.Circle005.geometry} material={materials['Material.002']} position={[0.002, -0.039, -0.112]}>
        <mesh geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/blazer.gltf')
